### ISSUE TITLE
Can't open on Ubuntu 20.04

### ISSUE THREAD

**Issue by madeindjs** [DaveJarvis/scrivenvar#62] opened 2020-08-13 07:11 UTC
I just downloaded version for linux on https://gitreleases.dev/gh/DaveJarvis/scrivenvar/latest/scrivenvar.bin and I run theses commands:

~~~bash
chmod u+x scrivenvar.bin
./scrivenvar.bin
~~~

But I get this error

~~~
/home/alexandre/.local/share/warp/packages/scrivenvar.bin/run.sh: ligne 6: /home/alexandre/.local/share/warp/packages/scrivenvar.bin/java/bin/java.exe: Aucun fichier ou dossier de ce type
~~~

**Comment by matthieu-vergne** [comment] 2020-08-16 15:45
Same error for me (Ubuntu 20.04 too).

**Comment by DaveJarvis** [comment] 2020-08-16 17:39
The problem is the `installer` shell script that builds the self-contained executables:

``` bash
utile_create_launch_script_linux() {
  $log "Create Linux launch script"

  cat > "${FILE_DIST_EXEC}" << __EOT
#!/usr/bin/env bash

readonly SCRIPT_SRC="\$(dirname "\${BASH_SOURCE[\${#BASH_SOURCE[@]} - 1]}")"
readonly SCRIPT_DIR="\$(cd "\${SCRIPT_SRC}" >/dev/null 2>&1 && pwd)"

"\${SCRIPT_DIR}/${ARG_JAVA_DIR}/bin/java.exe" -jar "\${SCRIPT_DIR}/${FILE_APP_JAR}" "\$@"
__EOT

  chmod +x "${FILE_DIST_EXEC}"
}
```

I had erroneously changed `java`  to `java.exe` when debugging why the Windows executable couldn't launch Java.

**Comment by luchev** [comment] 2020-08-16 17:45
I have the same issue on Arch (kernel 5.7.12-arch1-1).
I found the following script works for me:
```
#!/usr/bin/env bash

readonly SCRIPT_SRC="$(dirname "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}")"

"${SCRIPT_SRC}/java/bin/java" -jar "${SCRIPT_SRC}/scrivenvar.jar" "$@"
```

The SCRIPT_DIR variable is not needed.

**Comment by luchev** [comment] 2020-08-16 18:41
Also if I might suggesting appending `2>&1 >/dev/null &` to the end of the last row (`"${SCRIPT_SRC}/java/bin/java" -jar "${SCRIPT_SRC}/scrivenvar.jar" "$@"`). This would allow the editor to be started from the command line, without hijacking the terminal stdin/stdout. Also, this way you can close the terminal window after opening the editor and the editor will keep running.
The changed last line of the script would look like this: `"${SCRIPT_SRC}/java/bin/java" -jar "${SCRIPT_SRC}/scrivenvar.jar" "$@" 2>&1 >/dev/null &`

**Comment by DaveJarvis** [comment] 2020-08-23 19:47
Fixed in RC 7.

**Closed by DaveJarvis** 2020-08-23 19:47 UTC
Labels: bug
